In [1]:
import numpy as ns
a = ns.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [2]:
# Broadcasting 

var1 = ns.array([1,2,3,4,5])
var2 = ns.array([1,2,3,4,5])
print(var1 + var2)

[ 2  4  6  8 10]


In [3]:
var1 = ns.array([1,2,3,4,5])
var2 = ns.array([1,3,4,5])
print(var1 + var2)

# var1, no.of col = var2, no.of col 

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [4]:
var1 = ns.array([1,2,3,4,5])
print(var1.shape)

(5,)


In [5]:
var1 = ns.array([1,2,3,4,5],[1,2,3,4,4])
print(var1.shape)

TypeError: Field elements must be 2- or 3-tuples, got '1'

In [6]:
var1 = ns.array([[1,2,3,4,5],[1,2,3,4,4]])
print(var1.shape)

(2, 5)


In [12]:
# [1,2,3]    [1]   # output = [2,3,4]
#            [2]              [3,4,5]
#            [3]              [4,5,6]

var1 = ns.array([[1,2,3,4,5],[1,2,3,4,4]])
print(var1.shape)

var2 = ns.array([[1,2,3,5],[1,2,3,4]])
print(var2.shape)

print(var1 + var2)

(2, 5)
(2, 4)


ValueError: operands could not be broadcast together with shapes (2,5) (2,4) 

In [13]:
import numpy as np

var1 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1.shape)

var2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var2.shape)

print(var1 + var2)

(2, 4)
(2, 4)
[[2 4 6 8]
 [2 4 6 8]]


In [17]:
# Indexing and Slicing

# indexing
# 1-D

arr = np.array([9,8,7,6])
print(arr[1])
print(arr[-3])

8
8


In [20]:
# indexing
# 2-D

arr = np.array([[2,3,4],[6,7,8]])
print(arr)
print(arr.ndim)

print(arr[0,2])

[[2 3 4]
 [6 7 8]]
2
4


In [29]:
# 3-D

arr1 = np.array([[[2,3,4],[6,7,8]]])
print(arr1)
print(arr1.ndim)
print(arr1.shape)

print(arr1[0,1,1])

print(arr1[0,1,0])

[[[2 3 4]
  [6 7 8]]]
3
(1, 2, 3)
7
6


In [41]:
# Slicing

import numpy as nagaraj

arr1 = nagaraj.array([1,2,3,4,5,6,7,8])
print(" 2 To 5: ", arr1[2:5])
print(" upto To 5: ", arr1[:5])
print(" 2 To last: ", arr1[2:])
print("-Ve: ",arr1[-6:-1])
print(" sssssdsds ", arr1[::2])
print(" sssssdsds ", arr1[::-1])
print("Stop : ",arr1[1:6:2])


print(arr1)

 2 To 5:  [3 4 5]
 upto To 5:  [1 2 3 4 5]
 2 To last:  [3 4 5 6 7 8]
-Ve:  [3 4 5 6 7]
 sssssdsds  [1 3 5 7]
 sssssdsds  [8 7 6 5 4 3 2 1]
Stop :  [2 4 6]
[1 2 3 4 5 6 7 8]


In [45]:
arr2 = nagaraj.array([[1,2,3,4,5],[11,22,33,44,55],[111,222,333,444,555]])
print(arr2)

print("2-D indexing: ", arr2[1,1:])

print("2-D indexing: ", arr2[1,2:])

print("2-D indexing: ", arr2[2,1:])

[[  1   2   3   4   5]
 [ 11  22  33  44  55]
 [111 222 333 444 555]]
2-D indexing:  [22 33 44 55]
2-D indexing:  [33 44 55]
2-D indexing:  [222 333 444 555]


In [49]:
# NumPy Array Iterating

# for  loop
#  Iteration

# 1-D

import numpy as ns

arr = ns.array([1,2,3,4,54,566,7,7,8,8,9])
print(arr)
print(arr.size)

for i in arr:
    print(i)

[  1   2   3   4  54 566   7   7   8   8   9]
11
1
2
3
4
54
566
7
7
8
8
9


In [53]:
# 2-D

#  Iterration

arr1 = ns.array([[1,2,3,4],[5,6,7,8]])
print(arr1)

print()

for  j in arr1:
    for k in j:
        print(k)

[[1 2 3 4]
 [5 6 7 8]]

1
2
3
4
5
6
7
8


In [57]:
# 3-D

#  Iterration
import numpy as ns
arr2 = ns.array([[[1,2,3,4],[6,7,8,9]]])
print(arr2)

for i in arr2:
    for j in i:
        for k in j:
            print(K)



[[[1 2 3 4]
  [6 7 8 9]]]


NameError: name 'K' is not defined

In [58]:
# 3-D

import numpy as np

arr2 = np.array([[[1,2,3,4],[6,7,8,9]]])
print(arr2)

for i in arr2:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3 4]
  [6 7 8 9]]]
1
2
3
4
6
7
8
9


In [60]:
# Enumerater   idx's

import numpy as np

arr2 = np.array([[[1,2,3,4],[6,7,8,9]]])
print(arr2)

for i, d in np.ndenumerate(arr2):
    print(i,d)

[[[1 2 3 4]
  [6 7 8 9]]]
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 6
(0, 1, 1) 7
(0, 1, 2) 8
(0, 1, 3) 9


In [65]:
# Copy v/s  View

# COPY


import numpy as np

arr2 = np.array([ 1,2,3,4])

copy = arr2.copy()
view = arr2.view()
# Add new one
arr2[2] = 200;

print("Var : ",view)
print("Copy : ",copy)

Var :  [  1   2 200   4]
Copy :  [1 2 3 4]


In [68]:
# Join___ARRAY   and Split__ARRAY

import numpy as np

arr1 = np.array([1,2,3,4])
arr2 = np.array([9,8,7,6])

res_arr = np.concatenate((arr1,arr2))
print(res_arr)


[1 2 3 4 9 8 7 6]


In [69]:
# Concatenate

arr3 = np.array([[1,2],[3,4]])
arr4 = np.array([[9,8],[7,6]])

res = np.concatenate((arr3,arr4),axis=1)
print(arr3)
print()
print(arr4)
print()
print(res)

[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2 9 8]
 [3 4 7 6]]


In [70]:
# Using STACK

arr3 = np.array([1,2,3,4])
arr4 = np.array([5,6,7,8])

res = np.stack((arr3,arr4),axis=1)
print(arr3)
print()
print(arr4)
print()
print(res)

[1 2 3 4]

[5 6 7 8]

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [72]:
# Using STACK----H-----ROW

arr3 = np.array([1,2,3,4])
arr4 = np.array([5,6,7,8])

res = np.hstack((arr3,arr4))
print(arr3)
print()
print(arr4)
print()
print(res)

[1 2 3 4]

[5 6 7 8]

[1 2 3 4 5 6 7 8]


In [73]:
# Using STACK----V------COLUMN

arr3 = np.array([1,2,3,4])
arr4 = np.array([5,6,7,8])

res = np.vstack((arr3,arr4))
print(arr3)
print()
print(arr4)
print()
print(res)

[1 2 3 4]

[5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]


In [74]:
# Using STACK----D-------HEIGHT

arr3 = np.array([1,2,3,4])
arr4 = np.array([5,6,7,8])

res = np.dstack((arr3,arr4))
print(arr3)
print()
print(arr4)
print()
print(res)

[1 2 3 4]

[5 6 7 8]

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [75]:
# Array ROW/COL/HET


arr3 = np.array([1,2,3,4])
arr4 = np.array([5,6,7,8])

res = np.dstack((arr3,arr4))
res1 = np.vstack((arr3,arr4))
res2 = np.vstack((arr3,arr4))


print(res)
print(res1)
print(res2)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [78]:
# Split Array

# 1-D

import numpy as np

arr = np.array([1,2,3,4,5,6])

print(arr)

res = np.array_split(arr,3)
print(res)
print(type(res))

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>


In [80]:
# Split Array

# 2-D

import numpy as np

arr1 = np.array([[1,2],[3,4],[5,6]])

print(arr1)

res = np.array_split(arr1,3)
print(res)
print(type(res))

[[1 2]
 [3 4]
 [5 6]]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
<class 'list'>


In [85]:
# Search

import numpy as ns

arr = ns.array([1,2,3,4,5,6,7,8,9,12,4,56,3453,565])

x = np.where(arr == 56)
even = np.where((arr%2) != 0)  # print IDX
print(x)
print("even: ",even)

(array([11], dtype=int64),)
even:  (array([ 0,  2,  4,  6,  8, 12, 13], dtype=int64),)


In [91]:
# Search Sorted Array

import numpy as ns

arr1 = ns.array([1,2,3,3,3,3,3,4,5,6,7,8,9,12,565])

x1 = np.searchsorted(arr1,5)  # Where inert for inc order
print(x1)
print(arr1)

8
[  1   2   3   3   3   3   3   4   5   6   7   8   9  12 565]


In [92]:
# Sortded ------Incresing Order

arr10 = np.array([9,7,4,2,4,6,7,4,35,6,4,3,55,3,464,54,234])

print(arr10)

print(np.sort(arr10))

[  9   7   4   2   4   6   7   4  35   6   4   3  55   3 464  54 234]
[  2   3   3   4   4   4   4   6   6   7   7   9  35  54  55 234 464]


In [93]:
# Sortded ------Incresing Order  ----ChAR

arr10 = np.array(["a","E","I","o","U"])

print(arr10)

print(np.sort(arr10))

['a' 'E' 'I' 'o' 'U']
['E' 'I' 'U' 'a' 'o']


In [95]:
# Sortded ------Incresing Order----2-D _________ARRAY

arr10 = np.array([[9,7,4,2],[3,7,3,67]])

print(arr10)

print(np.sort(arr10))

[[ 9  7  4  2]
 [ 3  7  3 67]]
[[ 2  4  7  9]
 [ 3  3  7 67]]


In [96]:
#  Functions

#  Shuffle

import numpy as np

arr = np.array([1,2,3,4])

np.random.shuffle(arr)
print(arr)


[3 4 2 1]


In [100]:
# Unique

import numpy as np

arr = np.array([1,1,2,2,3,3,3,2,3,4])

x = np.unique(arr, return_index=True, return_counts=True)
print(x)

(array([1, 2, 3, 4]), array([0, 2, 4, 9], dtype=int64), array([2, 3, 4, 1], dtype=int64))


In [102]:
# Resize

arr1 = np.array([1,2,3,4,5,6])

a = np.resize(arr1,(2,3))
c = np.resize(arr1,(3,2))

print("---->",a)
print("---->",c)

----> [[1 2 3]
 [4 5 6]]
----> [[1 2]
 [3 4]
 [5 6]]


In [103]:
# Flatten

arr1 = np.array([1,2,3,4,5,6])

a = np.resize(arr1,(2,3))

print(a)

# return Same size

print(a.flatten())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [104]:
# insert and Delete

import numpy as np

a = np.array([1,2,3,4])

print(a)
added = np.insert(a, 2,2200)

print(added)

[1 2 3 4]
[   1    2 2200    3    4]


In [105]:
# insert

import numpy as np

a = np.array([1,2,3,4])

print(a)
added = np.insert(a, (2,4),2200)

print(added)

[1 2 3 4]
[   1    2 2200    3    4 2200]


In [112]:
# Delete

import numpy as np

a = np.array([1,2,3,4])

print(a)
delete = np.delete(a, 3)
delete1 = np.delete(a, 1)
delete2 = np.delete(a, 2)

print(delete)
print(delete1)
print(delete2)

[1 2 3 4]
[1 2 3]
[1 3 4]
[1 2 4]


In [114]:
# matrix

mat1 = np.matrix([[1,2],[3,4]])
mat2 = np.matrix([[1,2],[3,4]])

print(mat1)

print(mat2)

print("MUL: ",mat1 * mat2)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
MUL:  [[ 7 10]
 [15 22]]


In [116]:
# 3*3

import numpy as np

mat1 = np.matrix([[1,2,3],[3,4,6],[1,2,3]])
mat2 = np.matrix([[1,2,3],[3,4,6],[1,2,3]])
mat3 = np.matrix([[1,2,3],[3,4,6],[1,2,3]])

print(mat1)

print(mat2)

print(mat3)

print("MUL: ",mat1 * mat2 * mat3)

[[1 2 3]
 [3 4 6]
 [1 2 3]]
[[1 2 3]
 [3 4 6]
 [1 2 3]]
[[1 2 3]
 [3 4 6]
 [1 2 3]]
MUL:  [[ 82 132 198]
 [174 280 420]
 [ 82 132 198]]


In [118]:
# Matrix Function

# 1 Transpose

# 2. Swapaxes

# 3.Inverse

# 4.Power

# 5.Determinate

import numpy as mt

mat = mt.matrix([[1,2,3],[1,3,3]])
print(mat)

[[1 2 3]
 [1 3 3]]


In [119]:
# 1 Transpose

import numpy as mt

mat = mt.matrix([[1,1,1],[2,2,2]])
print(mat)
print()

print(mt.transpose(mat))
print()

[[1 1 1]
 [2 2 2]]

[[1 2]
 [1 2]
 [1 2]]



In [124]:
# 2. Swapaxes

import numpy as mt

mat = mt.matrix([[1,1,1],[2,2,2]])
print(mat)
print()

print(mt.swapaxes(mat,0,1))

[[1 1 1]
 [2 2 2]]

[[1 2]
 [1 2]
 [1 2]]


In [130]:
# 3.Inverse

import numpy as np

mat = np.array([[1,0],[0,1]])
print(mat)
print()

print(np.linalg.inv(mat))
print()


[[1 0]
 [0 1]]

[[1. 0.]
 [0. 1.]]



In [132]:
# 4.Power

import numpy as np

mat = np.array([[2,2],[2,1]])
print(mat)
print()

print(np.linalg.matrix_power(mat,2))  # mat ** 2 ===> mat * mat

[[2 2]
 [2 1]]

[[8 6]
 [6 5]]


In [134]:
# 5.Determinate

import numpy as np

mat = np.array([[2,2],[2,1]])
print(mat)
print()

print(np.linalg.det(mat))    #  a(qw-er) - b(we-we) + c(we-rt)

[[2 2]
 [2 1]]

-2.0
